spring:
  application:
    name: TaskTracker
  datasource:
    url: jdbc:postgresql://localhost:5433/task_tracker
    username: tracker_user
    password: tracker_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: false

logging:
  level:
    com.tracker.app: INFO
    org.hibernate.SQL: WARN